### ISSUE TITLE
[CCE] Increase Timeout (or decrease deployment time)

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#940] opened 2021-03-26 21:18 UTC
# Terraform Version

Terraform v0.14.7
- Using previously-installed opentelekomcloud/opentelekomcloud v1.23.4

# Affected Resource(s)

- opentelekomcloud_cce_cluster_v3

# Terraform Configuration Files
```hcl
# Set required Provider (source and version)
terraform {
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = ">= 1.23.4"
    }
  }
}

# Configure OpenTelekomCloud VPC subnet
resource "opentelekomcloud_vpc_subnet_v1" "cce_cluster_subnet" {
  name       = "indicarus-cce-cluster-subnet"
  vpc_id     = var.indicarus_vpc_id
  cidr       = var.cce_cluster_subnet_cidr

  gateway_ip = var.cce_cluster_subnet_gateway_ip

  tags = {
    terraform = "true"
  }
}

# Configure OpenTelekomCloud network security group
resource "opentelekomcloud_networking_secgroup_v2" "cce_cluster_sg" {
  name        = "indicarus-cce-cluster-sg"
  description = "Security group for a CCE cluster."
}

# Configure OpenTelekomCloud network security group rule
resource "opentelekomcloud_networking_secgroup_rule_v2" "cce_cluster_sg_rule" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 9998
  port_range_max    = 9998
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = opentelekomcloud_networking_secgroup_v2.cce_cluster_sg.id
}

# Configure OpenTelekomCloud EIP
resource "opentelekomcloud_vpc_eip_v1" "cce_cluster_eip" {
  publicip {
    type       = "5_bgp"
  }
  bandwidth {
    name        = "indicarus-cce-cluster-bandwidth"
    size        = var.cce_cluster_eip_bandwidth_size
    share_type  = "PER"
    charge_mode = "traffic"
  }
}

# Configure OpenTelekomCloud CCE cluster
resource "opentelekomcloud_cce_cluster_v3" "cce_cluster" {
  name        = "indicarus-cce-cluster"
  description = "Kubernetes cluster to run Tika Server."

  cluster_type           = "VirtualMachine"
  flavor_id              = var.cce_cluster_flavor
  cluster_version        = var.cce_cluster_version
  vpc_id                 = var.indicarus_vpc_id
  subnet_id              = opentelekomcloud_vpc_subnet_v1.cce_cluster_subnet.id
  container_network_type = "overlay_l2"
  authentication_mode    = var.cce_cluster_authentication_mode
  eip                    = opentelekomcloud_vpc_eip_v1.cce_cluster_eip.publicip[0].ip_address
}

# Configure OpenTelekomCloud compute keypair
resource "opentelekomcloud_compute_keypair_v2" "cce_node_pool_keypair" {
  name       = "indicarus-cce-node-pool-keypair"
  public_key = var.cce_node_pool_keypair_public_key
}

# Configure OpenTelekomCloud CCE node pool
resource "opentelekomcloud_cce_node_pool_v3" "cce_node_pool" {
  cluster_id         = opentelekomcloud_cce_cluster_v3.cce_cluster.id
  name               = "indicarus-cce-node-pool"
  os                 = var.cce_node_pool_os
  flavor             = var.cce_node_pool_flavor
  initial_node_count = var.cce_node_pool_initial_node_count
  subnet_id          = opentelekomcloud_vpc_subnet_v1.cce_cluster_subnet.id
  availability_zone  = var.cce_node_pool_availability_zone
  key_pair           = opentelekomcloud_compute_keypair_v2.cce_node_pool_keypair.name

  scale_enable             = true
  min_node_count           = var.cce_node_pool_min_node_count
  max_node_count           = var.cce_node_pool_max_node_count
  scale_down_cooldown_time = var.cce_node_pool_scale_down_cooldown_time
  priority                 = 1

  root_volume {
    size       = var.cce_node_pool_root_volume_size
    volumetype = var.cce_node_pool_root_volumetype
  }
  data_volumes {
    size       = var.cce_node_pool_data_volumes_size
    volumetype = var.cce_node_pool_data_volumetype
  }
}

```

# Debug Output/Panic Output

![image](https://user-images.githubusercontent.com/13590797/112692925-04a7dc80-8e80-11eb-9a91-7576c2fe43bd.png)

# Steps to Reproduce

1. `terraform apply` // any cce cluster

# Expected Behavior
Should be successful on first try. 

# Actual Behavior
Fails.

# Important Factoids

# References

**Comment by outcatcher** [comment] 2021-03-29 06:31
@DanielHabenicht have you tried to [set resource timeout](https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts) for your node pools? How long timeout should be enough? Acceptance tests seem to be passing with the current value, so it's not clear for me.

**Comment by DanielHabenicht** [comment] 2021-03-29 10:18
Yeah, sorry for not including it. Of course setting the timeout to a higher threshold solves the problem. 
We are at roughly 30 minutes. 

Can you share the config for the acceptance test? Maybe we are doing something differently that causes the slow down.

**Comment by outcatcher** [comment] 2021-03-29 11:22
I suppose, your configuration just uses different flavor/az or has bigger node count.
```hcl
resource "opentelekomcloud_cce_cluster_v3" "cluster" {
  name         = "opentelekomcloud-cce-np"
  cluster_type = "VirtualMachine"
  flavor_id    = "cce.s1.small"
  vpc_id       = "%s"
  subnet_id    = "%s"

  container_network_type = "overlay_l2"
  authentication_mode    = "rbac"
}

resource "opentelekomcloud_cce_node_pool_v3" "node_pool" {
  cluster_id         = opentelekomcloud_cce_cluster_v3.cluster.id
  name               = "opentelekomcloud-cce-node-pool"
  os                 = "EulerOS 2.5"
  flavor             = "s2.xlarge.2"
  initial_node_count = 1
  availability_zone  = "%s"
  key_pair           = "%s"

  root_volume {
    size       = 40
    volumetype = "SSD"
  }
  data_volumes {
    size       = 100
    volumetype = "SSD"
  }
}
```

AZ used - `eu-de-03`

**Comment by DanielHabenicht** [comment] 2021-03-30 19:46
Just to update you, I am still investigating. I don't know if it may be the issue but our deployment succeeds with all nodes being unavailable. I tried it with your config but get the same problem. 

So maybe has to with the nodes not becoming available (and so slowing it down?). Do you check with your test if the cluster can be used afterwards or just if the resources are created?

**Comment by outcatcher** [comment] 2021-03-30 20:11
@DanielHabenicht You can just ignore the issue status ― in case there will be more work to do here, we'll just reopen it :) 

Basically, terraform waits for node pool state (`status.phase`) empty (if the status is blank, the status is normal). Is node pool creation works fine via the console for you? 

It's quite strange for me to see node pool to be so long in status `Synchornizing` (our acceptance test run for like 15 minutes). Can you try it with as simple CCE node pool configuration as possible? Preferably, just terraform-managed VPC, subnet, cluster, and node group?

**Comment by DanielHabenicht** [comment] 2021-03-31 09:51
Tried it with your example but got the same issue:
```
resource "opentelekomcloud_vpc_v1" "cce_cluster_vpc" {
  name = "indicarus-cce-cluster-vpc"
  cidr = "172.16.0.0/24"

  tags = {
    terraform = "true"
  }
}

# Configure OpenTelekomCloud VPC subnet
resource "opentelekomcloud_vpc_subnet_v1" "cce_cluster_subnet" {
  name   = "indicarus-cce-cluster-subnet"
  cidr   = "172.16.0.0/24"
  vpc_id = opentelekomcloud_vpc_v1.cce_cluster_vpc.id

  gateway_ip = "172.16.0.1"

  tags = {
    terraform = "true"
  }
}

# Configure OpenTelekomCloud compute keypair
resource "opentelekomcloud_compute_keypair_v2" "cce_node_pool_keypair" {
  name       = "indicarus-cce-node-pool-keypair"
  public_key = var.cce_node_pool_keypair_public_key
}

# Configure OpenTelekomCloud CCE node pool
resource "opentelekomcloud_cce_cluster_v3" "cluster" {
  name         = "opentelekomcloud-cce-np"
  cluster_type = "VirtualMachine"
  flavor_id    = "cce.s1.small"
  vpc_id       = opentelekomcloud_vpc_v1.cce_cluster_vpc.id
  subnet_id    = opentelekomcloud_vpc_subnet_v1.cce_cluster_subnet.id

  container_network_type = "overlay_l2"
  authentication_mode    = "rbac"
}

resource "opentelekomcloud_cce_node_pool_v3" "node_pool" {
  cluster_id         = opentelekomcloud_cce_cluster_v3.cluster.id
  name               = "opentelekomcloud-cce-node-pool"
  os                 = "EulerOS 2.5"
  flavor             = "s2.xlarge.2"
  initial_node_count = 1
  availability_zone  = "eu-de-03"
  key_pair           = opentelekomcloud_compute_keypair_v2.cce_node_pool_keypair.name


  root_volume {
    size       = 40
    volumetype = "SSD"
  }
  data_volumes {
    size       = 100
    volumetype = "SSD"
  }
}
```

The nodes are not getting ready but stay unavailable: 
![image](https://user-images.githubusercontent.com/13590797/113125485-f0186b00-9216-11eb-96e5-060c84894c08.png)

If you want you want to cut ways short you can call me under my company phone number (we are both working at telekom).

**Comment by outcatcher** [comment] 2021-03-31 14:01
It clearly reproduces for me with your configuration. Will investigate further.

**Comment by DanielHabenicht** [comment] 2021-04-01 10:11
Just a tip, maybe it has something to do with #948. Because if the cluster is deployed via the UI the Security Group is automatically created: 
![image](https://user-images.githubusercontent.com/13590797/113279433-5965b000-92e3-11eb-9c7c-88c6db869fe3.png)

**Comment by outcatcher** [comment] 2021-04-02 09:12
@DanielHabenicht security groups are automatically created during cluster creation via the API too, so it doesn't seem to be the reason. So I'm still trying different configurations to find the reason.

**Comment by outcatcher** [comment] 2021-04-05 17:04
@DanielHabenicht I'm a bit stuck in the investigation, so I addressed a question to a person who is handling CCE issues on OTC side. I hope he will clarify this case.

**Comment by outcatcher** [comment] 2021-04-08 11:25
Internal issue reference:
https://jira.tsi-dev.otc-service.com/browse/OCS-3641

**Comment by dombisza** [comment] 2021-04-08 11:55
@DanielHabenicht please add dns configuration to the subnet like this:
```
resource "opentelekomcloud_vpc_subnet_v1" "cce_cluster_subnet" {
  name   = "ak-cce-cluster-subnet"
  cidr   = "172.16.0.0/16"
  vpc_id = opentelekomcloud_vpc_v1.cce_cluster_vpc.id

  gateway_ip = "172.16.0.1"

  primary_dns = "100.125.4.25"
  secondary_dns = "8.8.8.8"
}

**Comment by outcatcher** [comment] 2021-04-09 15:01
@DanielHabenicht If it's working for you with DNS set up, I will close this issue in favor of #965

**Closed as completed by outcatcher** 2021-04-09 15:01 UTC

**Comment by DanielHabenicht** [comment] 2021-04-09 16:08
I will try it out next Monday and will provide feedback then! Thanks for investigating.

**Comment by DanielHabenicht** [comment] 2021-04-12 10:23
Works, thanks for the help!
