### ISSUE TITLE
[IMS] calc aksk signature fail:body too large

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1860] opened 2022-08-02 08:03 UTC
Hello,

uploading private images to IMS doesn't work anymore. Worked until last Thursday, I didn't check on Friday.

# Terraform provider version

```
Terraform v1.3.0-alpha20220706
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.30.2
```

# Affected Resource(s)

opentelekomcloud_images_image_v2

# Terraform Configuration Files

Module: [https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-ims
](https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-ims
)
```
module "RHEL7" {
  source = "../modules/terraform-opentelekomcloud-ims"

  image_name            = "Red_Hat_Enterprise_Linux_7-Vanilla"
  image_disk_format     = "vmdk"
  image_local_file_path = "/windows/D/OTC/rhel-7.9-x86_64-disk001.vmdk"
}

module "RHEL8" {
  source = "../modules/terraform-opentelekomcloud-ims"

  image_name            = "Red_Hat_Enterprise_Linux_8-Vanilla"
  image_disk_format     = "qcow2"
  image_local_file_path = "/windows/D/OTC/rhel-8.6-x86_64-kvm.qcow2"
}
```

# Debug Output/Panic Output

module.RHEL7.opentelekomcloud_images_image_v2.this: Still creating... [1m20s elapsed]

```
module.RHEL8.opentelekomcloud_images_image_v2.this: Still creating... [1m30s elapsed]
module.RHEL8.opentelekomcloud_images_image_v2.this: Still creating... [1m40s elapsed]
╷
│ Error: error while uploading file "/windows/D/OTC/rhel-8.6-x86_64-kvm.qcow2": Authentication Failed, error message: {"error_msg":"Incorrect IAM authentication information: calc aksk signature fail:body too large","error_code":"APIGW.0301","request_id":"56b11a498c50f50f4d5889684140a202"}
│ 
│ 
│   with module.RHEL8.opentelekomcloud_images_image_v2.this,
│   on ../modules/terraform-opentelekomcloud-ims/main.tf line 1, in resource "opentelekomcloud_images_image_v2" "this":
│    1: resource "opentelekomcloud_images_image_v2" "this" {
│ 
╵
╷
│ Error: error while uploading file "/windows/D/OTC/rhel-7.9-x86_64-disk001.vmdk": Authentication Failed, error message: {"error_msg":"Incorrect IAM authentication information: calc aksk signature fail:body too large","error_code":"APIGW.0301","request_id":"44c2728d52b0029a807be8a7c292d2a3"}
│ 
│ 
│   with module.RHEL7.opentelekomcloud_images_image_v2.this,
│   on ../modules/terraform-opentelekomcloud-ims/main.tf line 1, in resource "opentelekomcloud_images_image_v2" "this":
│    1: resource "opentelekomcloud_images_image_v2" "this" {
│ 
╵
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Images are uploaded and ready for deployment.

# Actual Behavior

Error happens always and around trhe 1:30 to 1:40 minute marks.
In the Webconsole, the Images are registered and have status "Creating". This state persists seemingly forever; additional apply retries just lead to "more of the same".

# Important Factoids

OTC public cloud, eu-de
Happens with all disk formats.

# References

**Comment by anton-sidelnikov** [comment] 2022-08-02 08:34
@rramge which size of the image do you use?

**Comment by rramge** [comment] 2022-08-02 09:56
The disk size of the image itself is 64 GB.

I tested with min_disk_gb values of 40 (which is also the provider default value if null), 64 and 100.

Until recently the OTC behaviour was that if a min_disk_gb value was lower than the actual image disk size, then the value was updated in-place after the apply.  But I am not getting so far anymore today.

[EDIT]  I also tried with an image which only has 32 GB disk size, same result.

**Comment by anton-sidelnikov** [comment] 2022-08-04 09:30
Created internal ticket: OST-17401

**Comment by anton-sidelnikov** [comment] 2022-08-05 07:51
Hello @rramge can you check this: https://support.huaweicloud.com/intl/en-us/devg-apisign/api-sign-0001.html?

**Comment by rramge** [comment] 2022-08-05 09:41
Yes, that's possible. But since there are no signatures calculated by the end user (it's not a resource argument or whatever), this is either an internal problem or something is missing in the provider code. So there's nothing that can be done on the terraform end-user's side.
And don't forget: It worked until last week.

And it's not like we have any options on the provider level, besides maybe a missing header:

```
// Upload uploads an image file.
func Upload(client *golangsdk.ServiceClient, id string, data io.Reader) (r UploadResult) {
	_, r.Err = client.Put(uploadURL(client, id), data, nil, &golangsdk.RequestOpts{
		MoreHeaders: map[string]string{"Content-Type": "application/octet-stream"},
		OkCodes:     []int{204},
	})
	return
}
```

My two cents: I think it's an OTC internal problem in IMS or a gateway. AKSK-related errors were very common, but until now they were always false alarms.

**Comment by anton-sidelnikov** [comment] 2022-08-05 10:49
Yes, i will investigate this deeper, may be some header was changed/added on backend side

**Comment by anton-sidelnikov** [comment] 2022-09-20 11:44
@rramge Please check again, currently it works at least for 40gb images

**Comment by rramge** [comment] 2022-09-20 12:11
@anton-sidelnikov I tested again as requested.

If the Disk size is exactly 40 GB, uploading works and the image is ready for use in the web console.
All other sizes (lower and higher) fail with the described behaviour.

KR,

Ralf

**Comment by anton-sidelnikov** [comment] 2022-09-22 08:57
@rramge Please reproduce again, and attach latest error

**Comment by rramge** [comment] 2022-09-22 09:14
@anton-sidelnikov sure. Here you go. As you can see in the lines at the top, the 40 GB image worked, others (32 and 64 GB)  failed during the process.

```
module.RHEL8.opentelekomcloud_images_image_v2.this: Still creating... [1m50s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [2m0s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [2m10s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [2m20s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [2m30s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [2m40s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [2m50s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [3m0s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [3m10s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Still creating... [3m20s elapsed]
module.Empty40GB.opentelekomcloud_images_image_v2.this: Creation complete after 3m26s [id=5c9c21cb-00b0-47e1-a0c0-d4a2f49a9ce2]
╷
│ Error: error while uploading file "/windows/D/OTC/rhel-7.9-x86_64-disk001.vmdk": Authentication Failed, error message: {"error_msg":"Incorrect IAM authentication information: calc aksk signature fail:body too large","error_code":"APIGW.0301","request_id":"fea3cdf584002b664d31a3227161b5e8"}
│ 
│ 
│   with module.RHEL7.opentelekomcloud_images_image_v2.this,
│   on ../modules/terraform-opentelekomcloud-ims/main.tf line 1, in resource "opentelekomcloud_images_image_v2" "this":
│    1: resource "opentelekomcloud_images_image_v2" "this" {
│ 
╵
╷
│ Error: error while uploading file "/windows/D/OTC/rhel-8.6-x86_64-kvm.qcow2": Authentication Failed, error message: {"error_msg":"Incorrect IAM authentication information: calc aksk signature fail:body too large","error_code":"APIGW.0301","request_id":"02fb547f37a37c112136dd0b41620892"}
│ 
│ 
│   with module.RHEL8.opentelekomcloud_images_image_v2.this,
│   on ../modules/terraform-opentelekomcloud-ims/main.tf line 1, in resource "opentelekomcloud_images_image_v2" "this":
│    1: resource "opentelekomcloud_images_image_v2" "this" {
│ 
╵
[rramge@ol9 examples.local]$ terraform version
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.4
[rramge@ol9 examples.local]$ 

```

**Comment by anton-sidelnikov** [comment] 2023-01-11 16:34
Answer from backend team: it looks like this is expected behavior.
According to IAM documentation:
https://docs.otc.t-systems.com/api/iam/iam_02_0510.html 

AK/SK-based authentication supports API requests with a body not larger than 12 MB. For API requests with a larger body, token-based authentication is recommended.

Another documentation will be fixed.

**Closed as completed by anton-sidelnikov** 2023-01-11 16:34 UTC
Labels: otc-issue
