### ISSUE TITLE
Enhance TF for new DMS and DMS API v2

### ISSUE THREAD

**Issue by cboelle** [opentelekomcloud/terraform-provider-opentelekomcloud#2681] opened 2024-10-14 07:27 UTC
# Description of the enhancement
For the users of the new DMS service it will be important to:
•	Configure number of brokers (new flexibility)
•	Create new single instances
•	Create new Kafka 3.x clusters

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/dms_instance_v2

Current issues:

- Current version seems using v1 data source (to specify product_id) which is not compatible 
- engine_version 3.4 should be listed in documentation and be used as new default
- New optional broker number is needed to extend cluster to 4,5,6, … brokers during instance creation
- New examples needed: 1 for single instance and 1 for kafka 3.x cluster

**Comment by anton-sidelnikov** [comment] 2024-10-14 08:38
Hi @cboelle, duplicate of #2596, we already updated DMS resources, please wait for next releases.

**Comment by anton-sidelnikov** [comment] 2024-10-22 14:08
@artem-lifshits please update documentation and add extra examples

**Comment by anton-sidelnikov** [comment] 2024-11-28 10:55
Documentation was updated

**Closed as completed by anton-sidelnikov** 2024-11-28 10:55 UTC
Labels: enhancement
