### ISSUE TITLE
Bucket SSE-KMS Encryption Key can not be set via Terraform

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1160] opened 2021-06-24 15:11 UTC
# Terraform Version

0.14.8

# Provider Version

1.24.1

# Affected Resource(s)

opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_obs_bucket" "doc_bucket" {
  bucket = var.bucket_name
  acl    = "private"
  tags   = var.tags
  server_side_encryption {
    algorithm  = "aws:kms"
    kms_key_id = var.bucket_kms_key_id
  }
  versioning = false
}
```
# Debug Output/Panic Output

```
  ~ resource "opentelekomcloud_obs_bucket" "doc_bucket" {
        id                 = "nmcloud-dev1-docs"
        tags               = {
            "customer"    = "DTAG"
            "environment" = "DEV1"
            "instance"    = "NMCLOUD"
        }
        # (7 unchanged attributes hidden)

      ~ server_side_encryption {
          ~ algorithm  = "kms" -> "aws:kms"
            # (1 unchanged attribute hidden)
        }
    }
```

# The Problem
Bucket level KMS encryption keys can not be set properly via Terraform. After applying the above configuration the key appears absent on the cloud console UI:

![Screenshot from 2021-06-24 17-04-01](https://user-images.githubusercontent.com/70644420/123287411-016bcd80-d50f-11eb-93fb-a93316377742.png)
![Screenshot from 2021-06-24 17-04-30](https://user-images.githubusercontent.com/70644420/123287435-03ce2780-d50f-11eb-9745-7e3a61cd7d87.png)

When set manually from UI, Terraform sees the difference `"kms" -> "aws:kms"` so it is possible that there is a mistake in the mandatory `algorithm = "aws:kms"`

Furthermore, terraform can not remove the keys set on the bucket either.

# Steps to Reproduce

Create a bucket with bucket encryption key

**Comment by outcatcher** [comment] 2021-06-24 15:50
When I disable validation and  set the algorithm to `kms`, the following error appears:
```
╷
│ Error: error setting bucket encryption: obs: service returned error: Status=400 Bad Request, Code=InvalidArgument, Message=The configuration of bucket encryption contains illegal SSE algorithm, RequestId=0000017A3EA6B33545D5F8D16AE39E76
│ 
│   with opentelekomcloud_obs_bucket.b,
│   on test.tf line 1, in resource "opentelekomcloud_obs_bucket" "b":
│    1: resource "opentelekomcloud_obs_bucket" "b" {
│ 
╵

```

It seems to be an issue in OTC. I will create internal incident for that.

**Comment by outcatcher** [comment] 2021-06-24 15:55
Internal inicdent created: 
https://jira.tsi-dev.otc-service.com/browse/STO-5048

**Comment by outcatcher** [comment] 2021-06-30 07:56
Support of `kms` algorithm prohibits using `aws:kms`, so it's a backward-incompatible change.
Will require regression test on all OBS resources.

**Comment by outcatcher** [comment] 2021-07-01 10:43
There is a problem currently: `kms` algorithm requires using the `OBS` signature, switching OBS to S3-incompatible mode. This mode breaks encryption and bucket policy rules. 
We have no documentation of this mode currently.
Changes for rules is quite big, there should be 
```json
        {
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "ID": [
                  "*"
                ]
              },
              "Action": [
                "*"
              ],
              "Resource": [
                "tf-test-bucket-2185738448437901391",
                "tf-test-bucket-2185738448437901391/*"
              ]
            }
          ]
        }
```
instead of s3-like
```json
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  "*"
                ]
              },
              "Action": [
                "s3:*"
              ],
              "Resource": [
                "arn:aws:s3:::tf-test-bucket-2185738448437901391/*",
                "arn:aws:s3:::tf-test-bucket-2185738448437901391"
              ]
            }
          ]
        }
```

So this change (implemented in #1180) shouldn't be merged until we have documentation on how it should really work.

**Comment by outcatcher** [comment] 2021-07-01 11:03
Internal issue for tracking documentation progress:
https://jira.tsi-dev.otc-service.com/browse/STO-5205

**Comment by aengelhorn** [comment] 2021-07-18 19:28
I ran into the same problem in the meantime - is there a possible or recommended workaround besides doing everything manually or letting the buckets unencrypted?

**Comment by lego963** [comment] 2021-07-19 07:37
@aengelhorn you can use `aws:kms` with `kms_id` and objects will be encrypted, but UI won't show KMS settings.

**Comment by philippeckel** [comment] 2022-01-24 18:11
Never mind, all good. Read the documentation again where it now clearly states:

```
Note

Only base project (e.g. eu-de) KMS keys can be used for the encryption
```
Doing so did indeed encrypt the bucket.

---

Any update on that one?

Facing same problem here and @lego963 your suggestion is exactly what we're doing:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
  # module.infrastructure.module.obs.module.xxx.opentelekomcloud_kms_key_v1.xxx will be created
  + resource "opentelekomcloud_kms_key_v1" "xxx" {
      + creation_date           = (known after apply)
      + default_key_flag        = (known after apply)
      + domain_id               = (known after apply)
      + expiration_time         = (known after apply)
      + id                      = (known after apply)
      + is_enabled              = true
      + key_alias               = "xxx"
      + key_description         = "Key to encrypt bucket"
      + origin                  = (known after apply)
      + pending_days            = "7"
      + realm                   = (known after apply)
      + scheduled_deletion_date = (known after apply)
    }
  # module.infrastructure.module.obs.module.xxx.opentelekomcloud_obs_bucket.xxx will be created
  + resource "opentelekomcloud_obs_bucket" "xxx" {
      + acl                = "private"
      + bucket             = "xxx"
      + bucket_domain_name = (known after apply)
      + force_destroy      = false
      + id                 = (known after apply)
      + region             = (known after apply)
      + storage_class      = "STANDARD"
      + versioning         = false
      + logging {
          + target_bucket = (known after apply)
          + target_prefix = "log/"
        }
      + server_side_encryption {
          + algorithm  = "aws:kms"
          + kms_key_id = (known after apply)
        }
    }
  # module.infrastructure.module.obs.module.xxx.opentelekomcloud_obs_bucket.xxx will be created
  + resource "opentelekomcloud_obs_bucket" "xxx" {
      + acl                = "log-delivery-write"
      + bucket             = "xxx"
      + bucket_domain_name = (known after apply)
      + force_destroy      = false
      + id                 = (known after apply)
      + region             = (known after apply)
      + storage_class      = "COLD"
      + versioning         = false
    }
Plan: 3 to add, 0 to change, 0 to destroy.
module.infrastructure.module.obs.module.xxx.opentelekomcloud_kms_key_v1.xxx: Creating...
module.infrastructure.module.obs.module.xxx.opentelekomcloud_obs_bucket.xxx: Creating...
module.infrastructure.module.obs.module.xxx.opentelekomcloud_obs_bucket.xxx: Creation complete after 0s [id=xxx]
module.infrastructure.module.obs.module.xxx.opentelekomcloud_kms_key_v1.xxx: Still creating... [10s elapsed]
module.infrastructure.module.obs.module.xxx.opentelekomcloud_kms_key_v1.xxx: Creation complete after 10s [id=xxxxxxxxxxxxxxxxxxxxxxx]
module.infrastructure.module.obs.module.xxx.opentelekomcloud_obs_bucket.xxx: Creating...
╷
│ Error: error setting bucket encryption: obs: service returned error: Status=403 Forbidden, Code=AccessDenied, Message=Access Denied, RequestId=xxxxxxxxxxxxxxxxxxxx
│ 
│   with module.infrastructure.module.obs.module.xxx.opentelekomcloud_obs_bucket.xxx,
│   on ../../infrastructure/obs/xxx/main.tf line 7, in resource "opentelekomcloud_obs_bucket" "xxx":
│    7: resource "opentelekomcloud_obs_bucket" "xxx" {
│ 
╵
Releasing state lock. This may take a few moments...
Cleaning up file based variables 00:00
ERROR: Job failed: command terminated with exit code 1
```

So what's the solution now?

**Comment by kocsvin** [comment] 2022-03-25 14:29
I am running into same issue,  I am creating kms_key_v1 and passing its id to obs_bucket , and I get Error: error setting bucket encryption: ... Resources are created but default encryption is not enabled. I am getting the same error when I do terraform destroy , and resources are not being destroyed

**Closed as completed** 2022-03-29 12:54 UTC
Labels: breaking-change, otc-issue
