### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by strowi** [opentelekomcloud/terraform-provider-opentelekomcloud#2152] opened 2023-04-27 11:45 UTC
# Terraform provider version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.34.2

# Affected Resource(s)

- opentelekomcloud_identity_user_v3
- opentelekomcloud_identity_group_v3
- opentelekomcloud_identity_group_membership_v3
- opentelekomcloud_identity_role_v3
- 
# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
```hcl
resource "opentelekomcloud_identity_user_v3" "user_1" {
  name     = "user_1"
  password = "oih249h42EF51#+*"
  enabled  = true
}

resource "opentelekomcloud_identity_group_v3" "group_1" {
  name        = "KMSAdministrator-audit-logs"
  description = "This is a test group"
}


resource "opentelekomcloud_identity_group_membership_v3" "membership_1" {
  group = opentelekomcloud_identity_group_v3.group_1.id
  users = [opentelekomcloud_identity_user_v3.user_1.id]
}

resource "opentelekomcloud_identity_role_v3" "role" {
  description   = "role"
  display_name  = "test"
  display_layer = "domain"
  statement {
    effect = "Allow"
    action = [
      "kms:dek:crypto",
      "kms:dek:create",
      "kms:cmk:generate",
      "kms:cmk:crypto"
    ]
    resource = ["kms:*:*:KeyId:*"]
  }
}

terraform {
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "~> 1.34.2"
    }
  }
  required_version = "1.4.6"
}

provider "opentelekomcloud" {
  # agency_name        = ""
  # agency_domain_name = 
  delegated_project = "eu-de"
  access_key        = ""
  secret_key        = ""
  domain_name       = ""
  auth_url          = "https://iam.eu-de.otc.t-systems.com/v3"
}
```

# Debug Output/Panic Output

https://gist.github.com/strowi/47613251543d10b676d964d9626b66a2

# Steps to Reproduce

1. `terraform init && terraform plan`

# Expected Behavior

success

# Actual Behavior

Planning failed

# Important Factoids

# References

**Comment by artem-lifshits** [comment] 2023-04-27 18:03
Hello @strowi I wasn't able to reproduce the issue, could you send environment variables you are using to run the config?
Please delete all sensitive data before submitting.

Thanks!

**Comment by artem-lifshits** [comment] 2023-04-27 19:10
Also the issue may be caused by `clouds.yaml` file with `null` value inside.

**Comment by strowi** [comment] 2023-04-28 08:37
Thx for the response @artem-lifshits . There are no environment-variables set. For testing purposes i added the ak/sk and domain-name in the provider configuration. Just created a new folder c&p the above code with credentials and get the same error. 
There is no clouds.yaml in the folder.

PS: Weirdly enough going back to provider "1.24.1" i get an error about a missing resources:

```
 Error: Unsupported argument
│ 
│   on main.tf line 30, in resource "opentelekomcloud_identity_role_v3" "role":
│   30:     resource = ["kms:*:*:KeyId:*"]
│ 
│ An argument named "resource" is not expected here.
```

Removing the "opentelekomcloud_identity_role_v3" the rest works...

**Comment by artem-lifshits** [comment] 2023-04-28 09:06
@strowi I think `resource` parameter wasn't supported on `v1.24.1`.
Yesterday I found the exact place in code which causes the error. The only way I was able to reproduce it was by creating a `clouds.yaml` file with `null` value inside, it's a bug and going to be fixed on next release.

Could you try creating `clouds.yaml` file in `~/.config/openstack`? Leaving it empty should fix the problem.

**Comment by strowi** [comment] 2023-04-28 09:44
Yes, the empty `~/.config/openstack/clouds.yaml` seems to have solved it. Thanks for the quick response!

**Comment by artem-lifshits** [comment] 2023-05-04 12:22
Issue is fixed in latest release.

**Closed as completed** 2023-05-04 12:22 UTC
Labels: bug
