### ISSUE TITLE
automatic acceptance test on pr

### ISSUE THREAD

**Issue by vladimirvshivkov** [opentelekomcloud/terraform-provider-opentelekomcloud#1822] opened 2022-07-19 07:06 UTC
# Description of the enhancement
We have to figure out the way to run acc test on module modified PR

**Comment by anton-sidelnikov** [comment] 2022-12-23 16:32
This is duplicate of #1290, currently we preparing tests for auto run.

**Closed as completed by anton-sidelnikov** 2022-12-23 16:32 UTC
Labels: enhancement
