### ISSUE TITLE
502 The backend server is unreachable

### ISSUE THREAD

**Issue by victorgetz** [opentelekomcloud/terraform-provider-opentelekomcloud#916] opened 2021-03-19 08:00 UTC
# Terraform Version
Terraform v0.13.3 and also on all other

# Affected Resource(s)
everything from provider "opentelekomcloud" and does not matter which provider version

If i make a Terraform plan or apply locally then i get very often a Error "The backend server is unreachable":

```
Error: Error retrieving OpenTelekomCloud Subnets: Expected HTTP response code [200] when accessing [GET https://vpc.eu-de.otc.t-systems.com/v1/.../subnets/...], but got 502 instead
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http:/
/www.w3.org/1999/xhtml"><head><META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=utf-8"/><title>Error</title><
/head><body><H2>Error</H2><table summary="Error" border="0" bgcolor="#FEEE7A" cellpadding="0" cellspacing="0" width="400"><tr><td><table
summary="Error" border="0" cellpadding="3" cellspacing="1"><tr valign="top" bgcolor="#FBFFDF" align="left"><td><STRONG>Error</STRONG><
/td></tr><tr valign="top" bgcolor="#FFFFFF"><td>The backend server is unreachable.<br/></td></tr></table></td></tr></table></body></html>
```

This issue just happens from outside of OTC if i execute it OTC internaly via for example Gitlab Runner everything works perfect (Because different routing and ip addresses of the OTC API Server).

parallelism= and max_retry=50 did not help

**Comment by outcatcher** [comment] 2021-03-19 08:05
Hi @victorgetz, this is a known and vastly reported issue with API gateway. We will add error 502 to the list of retryable errors.

**Comment by victorgetz** [comment] 2021-03-19 08:09
Thanks this issue exists already over a year but since i think yesterday the error message changed. Are the API gateway guys not able to fix it?

**Comment by outcatcher** [comment] 2021-03-19 08:18
Seems so. The situation become worse recently, so this problem was given a higher priority. Just hoping it will be fixed soon.

**Comment by outcatcher** [comment] 2021-03-22 07:57
Internal incident: https://jira.tsi-dev.otc-service.com/browse/OPERABILIT-2676

**Comment by outcatcher** [comment] 2021-03-22 09:31
Further actions depend on internal incident resolution

**Comment by gtema** [comment] 2021-04-06 14:52
can you please provide the source IP from which you get this error? We get observation that this issue depends on the specific source IPs and we want to find similarities to help localize the problem

**Comment by victorgetz** [comment] 2021-04-13 07:19
Do you mean my IP Address?

I can help you to find similarities. This Problem occurs every time if you don't have 100% stable internet connection or a good Upload Speed.

My colleague from Munich has zero Problems but he has a 1000MB Internet Connection and High Upload Speed.

Me and my other colleague having this issue we are living in different cities and have like 150MB Internet Connection.

If i make terraform apply over WIFI the error occurs more often.

**Comment by victorgetz** [comment] 2021-04-13 07:21
> Hi @victorgetz, this is a known and vastly reported issue with API gateway. We will add error 502 to the list of retryable errors.

Is this done already?

**Comment by gtema** [comment] 2021-04-13 07:26
Yes, I mean IP address.
The case is occurring for some IP even for requests sent from outside OTC, so internet connection on it's own is not causing that issue. At the moment source IP is the only "denominator" for the issue.

On the other side we have decided not to implement automatic retry do to the following considerations:
- this is a clear platform issue and need to be fixed
- there are too many tools, where we would have no possibility to implement retry. Addressing it only in some areas would cause inconsistency complains
- 502 on it's own is a "retryable" error, but according to all recommendations you can find in internet it should not be retried immediately, since problem is usually caused by the backend maintenance or overload. Simple retry will only make the situation worse.

**Comment by victorgetz** [comment] 2021-04-13 07:50
Hi my IP Address is 37.201.193.173

But the retry workaround seems to work like a charm.
Finally i can apply locally.

Thanks a lot !

**Comment by gtema** [comment] 2021-04-13 07:51
do you have a dynamic ip?

**Comment by victorgetz** [comment] 2021-04-13 07:55
Yes i have a dynamic ip

**Comment by artem-lifshits** [comment] 2023-01-16 10:19
Hello @victorgetz AFAIK API gateway settings were changed, could you please try to reproduce the issue?
Thanks.

**Comment by anton-sidelnikov** [comment] 2023-01-27 12:44
Now we have retry function in sdk for these type of errors.

**Closed as completed by anton-sidelnikov** 2023-01-27 12:44 UTC
Labels: otc-issue
