### ISSUE TITLE
CSS Volume Encryption not working

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#1337] opened 2021-08-28 11:47 UTC
# Terraform Version
Terraform v1.0.5
on windows_amd64

# Affected Resource(s)
- opentelekomcloud_css_cluster_v1

# Terraform Configuration Files
```hcl
data "opentelekomcloud_kms_key_v1" "storage_encryption_key" {
  key_alias = "storage-encryption-key"
}

# Configure OpenTelekomCloud CSS cluster
resource "opentelekomcloud_css_cluster_v1" "css_cluster" {
  name             = "${var.root_name}-css-cluster"
  expect_node_num  = var.css_node_number
  enable_https     = "true"
  enable_authority = "true"
  admin_pass       = var.css_admin_pass

  node_config {
    flavor = var.css_flavor
    network_info {
      security_group_id = opentelekomcloud_networking_secgroup_v2.css_sg.id
      network_id        = opentelekomcloud_vpc_subnet_v1.css_subnet.id
      vpc_id            = var.vpc_id
    }
    volume {
      encryption_key = data.opentelekomcloud_kms_key_v1.storage_encryption_key.id
      volume_type    = var.css_volume_type
      size           = var.css_volume_size
    }

    availability_zone = var.css_availability_zone
  }

  timeouts {
    create = "30m"
  }
}
```

# Debug Output/Panic Output
Everything is nominal

# Steps to Reproduce
Create CSS Cluster with volume `encryption_key` set.

# Expected Behavior
Disk should be encrypted. 

# Actual Behavior
Its not. 

![image](https://user-images.githubusercontent.com/13590797/131216819-e7e7cd53-c367-4b13-a1db-3823e94a97ba.png)

**Comment by outcatcher** [comment] 2021-08-30 15:09
Also reproduced manually with `curl`. This seems to be an OTC issue, internal incident created:
https://jira.tsi-dev.otc-service.com/browse/OTCBIGDAI-1645

**Comment by outcatcher** [comment] 2021-08-30 15:11
Though there is still a mistake in CSS cluster creation related to the encryption, will be fixed in #1343

**Comment by Aloento** [comment] 2022-08-25 21:17
Status:SELECTED FOR DEVE

**Comment by Aloento** [comment] 2022-08-25 21:17
Status:SELECTED FOR DEV

**Comment by artem-lifshits** [comment] 2023-08-07 10:02
Issue is still not fixed, new ticket: https://jira.tsi-dev.otc-service.com/browse/OTCBIGDAI-3972

**Comment by mreichardt95** [comment] 2023-12-06 21:15
Is there any news on this? Issue still exists.

**Comment by artem-lifshits** [comment] 2024-02-08 12:23
Feature is being tested on staging env.

**Comment by artem-lifshits** [comment] 2024-03-26 10:08
@DanielHabenicht @mreichardt95 encryption is working now.

**Closed as completed by artem-lifshits** 2024-03-26 10:08 UTC
Labels: otc-issue
