### ISSUE TITLE
Enabling SSL for RDS instances

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1147] opened 2021-06-22 13:08 UTC
# Description of the enhancement
We are using terraform to create Relation Database Service resources in OTC. One of the parameters we would like to set is the SSL option on the DB configuration.

Currently we perform this as a manual task, and we wish to be able to set this flag via terraform. Ideally the certificate should also be exported as an attribute for the resource so that it can be passed to where it is needed without the need to manually download it.

The feature seems to be missing in the OTC API docs as well, however here is a screenshot to show the exact option we wish to have added to Terraform:
![RDS_ssl](https://user-images.githubusercontent.com/70644420/122929801-a3eb4b80-d36b-11eb-919a-acfd4747b854.jpg)

**Comment by lego963** [comment] 2021-06-22 13:30
This is duplicate of #936 and OTC issue for now :)
We need to wait ...

**Closed as completed by lego963** 2021-06-22 13:30 UTC
Labels: enhancement

**Comment by canaykin** [comment] 2021-06-22 13:32
Thank you for the update @lego963
