### ISSUE TITLE
Add support for setting user email

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/terraform-provider-opentelekomcloud#566] opened 2020-08-13 15:59 UTC
Customers need to have possibility to set user email (which will be in-sync with what UI shows. https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=update-user-detail#update-user is tested to work

**Comment by outcatcher** [comment] 2020-08-18 09:02
@gtema seems to be a duplicate of #551

**Comment by outcatcher** [comment] 2020-08-18 09:10
Will be fixed together with #551

**Closed as completed** 2020-08-18 09:13 UTC
Labels: SDK
