### ISSUE TITLE
RDS MySQL - can't find version `8.0`

### ISSUE THREAD

**Issue by tobiashoefler** [opentelekomcloud/terraform-provider-opentelekomcloud#1741] opened 2022-05-23 07:57 UTC
# Terraform provider version
```
Terraform version: 1.1.9
Provider: opentelekomcloud/opentelekomcloud v1.29.3
```

# Affected Resource(s)
`- opentelekomcloud_rds_instance_v3`

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_rds_instance_v3" "instance" {
  name              = var.name
  availability_zone = var.availability_zones

  security_group_id   = var.security_group_id
  subnet_id           = var.subnet_id
  vpc_id              = var.vpc_id
  flavor              = var.flavor
  ha_replication_mode = var.ha_replication_mode

  db {
    password = var.db_root_password
    type     = var.db_type
    version  = var.db_version
    port     = var.db_port
  }

  volume {
    disk_encryption_id = var.kms_key_id
    type               = "ULTRAHIGH"
    size               = var.volume_size
  }
  backup_strategy {
    start_time = "02:00-03:00"
    keep_days  = 5
  }
```
Everything is in variables. var.db_version is "8.0", var.db_type is "MySQL"

# Debug Output/Panic Output
```
│ Error: 1 error occurred:
│ 	* can't find version `8.0`
│ 
│ 
│ 
│   with module. .... .opentelekomcloud_rds_instance_v3.instance,
│   on ../.  .....   /rds/main.tf line 1, in resource "opentelekomcloud_rds_instance_v3" "instance":
│    1: resource "opentelekomcloud_rds_instance_v3" "instance" {
```

# Actual Behavior
The code was working fine for months. Since Saturday, all of a sudden the above message breaks the build. It works if I change the version to "8.0.21" but this gets changed on the OTC to 8.0 and is reported as: "Objects have changed outside of Terraform" afterwards

**Comment by canaykin** [comment] 2022-05-23 12:03
It appears the issue is isolated to MySQL but not isolated to version 8.0.x

**Comment by rhtot** [comment] 2022-05-23 13:05
got the same today
Error: can't find version `8.0`

  on ../../.../.../..., in resource "opentelekomcloud_rds_parametergroup_v3" "db_param_group":
  89: resource "opentelekomcloud_rds_parametergroup_v3" "db_param_group" {
  
  After specifying minor version, it allows to run the plan, with same effect as seen on Tobias's comment.
  
  PS: Hi Can :D

**Comment by lego963** [comment] 2022-05-23 13:46
@tobiashoefler @canaykin @rhtot guys, it should be fixed soon (I hope). For now I can suggest you use meta-argument `ignore_changes`

Ticket created: https://jira.tsi-dev.otc-service.com/browse/OTCDB-1753

**Comment by lego963** [comment] 2022-05-23 13:55
@tobiashoefler @canaykin @rhtot can you try again? This issue should be fixed

**Comment by rhtot** [comment] 2022-05-23 14:01
Hi @lego963 
lifecycle {
    ignore_changes = [listname[index]]
  }
  
  Did the trick, now I'm also trying without it to see if it is fixed. Thanks in advance!

**Comment by rhtot** [comment] 2022-05-23 14:06
fix confirmed, thanks @lego963 for being super fast!

**Closed as completed** 2022-05-23 14:12 UTC
Labels: otc-issue

**Comment by Dustlayer** [comment] 2022-05-24 09:19
Since yesterday terraform even tells me 
`can't find version '8.0.21'`

This error also appears if I add 
```
  lifecycle {
    ignore_changes = [db,]
  }
```

I've currently installed provider version 1.29.3.
Of course my whole Terraform deployment can't be applied like that.

When I create a RDS instance via console it also creates a MySQL DB with the Version 8.0.21, so I feel kind of fooled.
Do you have a hint for me how I can proceed and handle RDS updates?

**Comment by rhtot** [comment] 2022-05-24 09:24
@Dustlayer do you specify the version with the minor version? With provider version 1.26.2 now I only have to define the major version like 8.0. Haven't tested it with 1.29.3 yet as I need to do some minor refactoring, but if you can, maybe check with 1.26.2.

**Comment by Dustlayer** [comment] 2022-05-24 09:27
@rhtot I just found out that the version string "8.0" works again.
But will it stay that way?
Because if you have to change the (minor) version Terraform of course says "the RDS has to be replaced".

So was the real issue here, that the OTC backend said, that it doesn't know version "8.0" anymore?

**Comment by rhtot** [comment] 2022-05-24 09:34
@Dustlayer I believe so, as if you check the console, when creating an RDS instance manually, you only have the option to specify the major version (8.0, 5.7, 5.6 at the moment). This is by design I assume, therefore the minor version check happens only in the background. Now for example if one of your RDS instances is 8.0.20 while the other one is 8.0.21, being forced to define minor versions wouldn't make sense as a DB is not the resource that is often replaced.

**Comment by Dustlayer** [comment] 2022-05-24 09:38
@rhtot Then I'm assuming that I can stay on "8.0" now. We're just starting off with OTC, so this was a little confusing.
Thank you for clarifying!

**Comment by rhtot** [comment] 2022-10-11 09:05
Hi Rodion,

Just tested this and it works fine, from my point of view it is fixed. Also the workaround was working as well.

Thank you for the fast support!

Best Regards,
Robert
