### ISSUE TITLE
Creating opentelekomcloud_lb_loadbalancer_v3 with existing EIP fails

### ISSUE THREAD

**Issue by sfhl** [opentelekomcloud/terraform-provider-opentelekomcloud#1740] opened 2022-05-20 06:57 UTC
# Terraform provider version
```
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/terraform-providers/opentelekomcloud v1.29.3
```

# Affected Resource(s)
`opentelekomcloud_lb_loadbalancer_v3`

# Terraform Configuration Files
```hcl
...
  # opentelekomcloud_lb_loadbalancer_v3.cceelb-external-prod-project-app-ops will be created
  + resource "opentelekomcloud_lb_loadbalancer_v3" "cceelb-external-prod-project-app-ops" {
      + admin_state_up     = true
      + availability_zones = [
          + "eu-de-01",
        ]
      + created_at         = (known after apply)
      + id                 = (known after apply)
      + ip_target_enable   = (known after apply)
      + l4_flavor          = "90134454-f4ec-4c69-a156-b5ab3290a4bb"
      + l7_flavor          = "68124414-698a-4151-bc6c-09d430b3bc5c"
      + name               = "cceelb-external-prod-project-app-ops"
      + network_ids        = [
          + "a65405c5-69de-4f2d-811e-2a1402d4d18f",
        ]
      + router_id          = "48a44547-7870-4b0b-a36b-67feaafd0927"
      + subnet_id          = "a65405c5-69de-4f2d-811e-2a1402d4d18f"
      + updated_at         = (known after apply)
      + vip_address        = "192.168.13.3"
      + vip_port_id        = (known after apply)
    }
...
  # opentelekomcloud_vpc_eip_v1.prod-ops will be created
  + resource "opentelekomcloud_vpc_eip_v1" "prod-ops" {
      + id     = (known after apply)
      + region = (known after apply)

      + bandwidth {
          + charge_mode = "traffic"
          + name        = "eip-prod-ops"
          + share_type  = "PER"
          + size        = 300
        }

      + publicip {
          + ip_address = (known after apply)
          + port_id    = (known after apply)
          + type       = "5_gray"
        }
    }
...
```

# Debug Output/Panic Output
```
│ Error: error allocating EIP: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v1/XXXXXXXXXXXXXXXXXX/publicips], error message: {"code":"VPC.0501","message":"PublicIp type is invalid."}
│
│   with opentelekomcloud_vpc_eip_v1.prod-ops,
│   on main.tf line 188, in resource "opentelekomcloud_vpc_eip_v1" "prod-ops":
│  188: resource "opentelekomcloud_vpc_eip_v1" "prod-ops" {
│
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
All resources are created.

# Actual Behavior
It fails to create the EIP/bandwidth

**Comment by nfelger** [comment] 2022-05-20 09:47
I just came here to report the exact same problem…

**Comment by nfelger** [comment] 2022-05-20 12:55
So the issue is that `opentelekomcloud_vpc_eip_v1` cannot create EIPs of type `5_gray`? Can this be fixed? Is there a workaround?

**Comment by lego963** [comment] 2022-05-23 12:57
@sfhl @nfelger can you try this script pls? I don't have an explanation why your script isn't working.
```hcl
data "opentelekomcloud_vpc_subnet_v1" "this" {
  name = "subnet-do-not-delete-pls"
}

resource "opentelekomcloud_lb_loadbalancer_v3" "this" {
  admin_state_up = true
  availability_zones = [
    "eu-de-01",
  ]
  network_ids = [
    data.opentelekomcloud_vpc_subnet_v1.this.network_id
  ]
  router_id = data.opentelekomcloud_vpc_subnet_v1.this.vpc_id
  subnet_id = data.opentelekomcloud_vpc_subnet_v1.this.subnet_id

  public_ip {
    bandwidth_name       = "lb-bandwidth"
    ip_type              = "5_gray"
    bandwidth_size       = 10
    bandwidth_share_type = "PER"
  }
}
```

**Comment by nfelger** [comment] 2022-05-23 13:31
I (obviously?) don't have that subnet, so I ran this instead:

```hcl
resource "opentelekomcloud_vpc_v1" "this" {
  name = "nfelger-test-1"
  cidr = "10.0.0.0/20"
}

resource "opentelekomcloud_vpc_subnet_v1" "this" {
  name   = "nfelger-test-1"
  cidr   = cidrsubnet(opentelekomcloud_vpc_v1.this.cidr, 4, 1)
  vpc_id = opentelekomcloud_vpc_v1.this.id

  gateway_ip = cidrhost(cidrsubnet(opentelekomcloud_vpc_v1.this.cidr, 4, 1), 1)
}

resource "opentelekomcloud_lb_loadbalancer_v3" "this" {
  admin_state_up = true
  availability_zones = [
    "eu-de-01",
  ]
  network_ids = [
    opentelekomcloud_vpc_subnet_v1.this.network_id
  ]
  router_id = opentelekomcloud_vpc_subnet_v1.this.vpc_id
  subnet_id = opentelekomcloud_vpc_subnet_v1.this.subnet_id

  public_ip {
    bandwidth_name       = "lb-bandwidth"
    ip_type              = "5_gray"
    bandwidth_size       = 10
    bandwidth_share_type = "PER"
  }
}
```

This one completes fine, without any problems:
```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # opentelekomcloud_lb_loadbalancer_v3.this will be created
  + resource "opentelekomcloud_lb_loadbalancer_v3" "this" {
      + admin_state_up     = true
      + availability_zones = [
          + "eu-de-01",
        ]
      + created_at         = (known after apply)
      + id                 = (known after apply)
      + ip_target_enable   = (known after apply)
      + l4_flavor          = (known after apply)
      + l7_flavor          = (known after apply)
      + network_ids        = (known after apply)
      + router_id          = (known after apply)
      + subnet_id          = (known after apply)
      + updated_at         = (known after apply)
      + vip_address        = (known after apply)
      + vip_port_id        = (known after apply)

      + public_ip {
          + _managed              = (known after apply)
          + address               = (known after apply)
          + bandwidth_charge_mode = "traffic"
          + bandwidth_name        = "lb-bandwidth"
          + bandwidth_share_type  = "PER"
          + bandwidth_size        = 10
          + id                    = (known after apply)
          + ip_type               = "5_gray"
        }
    }

  # opentelekomcloud_vpc_subnet_v1.this will be created
  + resource "opentelekomcloud_vpc_subnet_v1" "this" {
      + availability_zone = (known after apply)
      + cidr              = "10.0.1.0/24"
      + dhcp_enable       = true
      + dns_list          = (known after apply)
      + gateway_ip        = "10.0.1.1"
      + id                = (known after apply)
      + name              = "nfelger-test-1"
      + network_id        = (known after apply)
      + primary_dns       = (known after apply)
      + region            = (known after apply)
      + secondary_dns     = (known after apply)
      + subnet_id         = (known after apply)
      + vpc_id            = (known after apply)
    }

  # opentelekomcloud_vpc_v1.this will be created
  + resource "opentelekomcloud_vpc_v1" "this" {
      + cidr   = "10.0.0.0/20"
      + id     = (known after apply)
      + name   = "nfelger-test-1"
      + region = (known after apply)
      + shared = (known after apply)
      + status = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opentelekomcloud_vpc_v1.this: Creating...
opentelekomcloud_vpc_v1.this: Creation complete after 6s [id=f571786d-9376-4fec-8f2b-55b5a905abfc]
opentelekomcloud_vpc_subnet_v1.this: Creating...
opentelekomcloud_vpc_subnet_v1.this: Creation complete after 8s [id=a87c0f89-436f-4789-a667-8c3d73769f52]
opentelekomcloud_lb_loadbalancer_v3.this: Creating...
opentelekomcloud_lb_loadbalancer_v3.this: Creation complete after 2s [id=e13211f9-1bc4-4459-8d89-6d7056d45056]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Comment by nfelger** [comment] 2022-05-23 13:41
@lego963 So I'd guess this has nothing to do with `opentelekomcloud_lb_loadbalancer_v3` but rather the `opentelekomcloud_vpc_eip_v1` resource?

Because this still fails:
```hcl
resource "opentelekomcloud_vpc_v1" "this" {
  name = "nfelger-test-1"
  cidr = "10.0.0.0/20"
}

resource "opentelekomcloud_vpc_subnet_v1" "this" {
  name   = "nfelger-test-1"
  cidr   = cidrsubnet(opentelekomcloud_vpc_v1.this.cidr, 4, 1)
  vpc_id = opentelekomcloud_vpc_v1.this.id

  gateway_ip = cidrhost(cidrsubnet(opentelekomcloud_vpc_v1.this.cidr, 4, 1), 1)
}

resource "opentelekomcloud_vpc_eip_v1" "this" {
  bandwidth {
    charge_mode = "traffic"
    name        = "eip-prod-ops"
    share_type  = "PER"
    size        = 100
  }

  publicip {
    type = "5_gray"
  }
}
```

Like so:
```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # opentelekomcloud_vpc_eip_v1.this will be created
  + resource "opentelekomcloud_vpc_eip_v1" "this" {
      + id     = (known after apply)
      + region = (known after apply)

      + bandwidth {
          + charge_mode = "traffic"
          + name        = "eip-prod-ops"
          + share_type  = "PER"
          + size        = 100
        }

      + publicip {
          + ip_address = (known after apply)
          + port_id    = (known after apply)
          + type       = "5_gray"
        }
    }

  # opentelekomcloud_vpc_subnet_v1.this will be created
  + resource "opentelekomcloud_vpc_subnet_v1" "this" {
      + availability_zone = (known after apply)
      + cidr              = "10.0.1.0/24"
      + dhcp_enable       = true
      + dns_list          = (known after apply)
      + gateway_ip        = "10.0.1.1"
      + id                = (known after apply)
      + name              = "nfelger-test-1"
      + network_id        = (known after apply)
      + primary_dns       = (known after apply)
      + region            = (known after apply)
      + secondary_dns     = (known after apply)
      + subnet_id         = (known after apply)
      + vpc_id            = (known after apply)
    }

  # opentelekomcloud_vpc_v1.this will be created
  + resource "opentelekomcloud_vpc_v1" "this" {
      + cidr   = "10.0.0.0/20"
      + id     = (known after apply)
      + name   = "nfelger-test-1"
      + region = (known after apply)
      + shared = (known after apply)
      + status = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opentelekomcloud_vpc_v1.this: Creating...
opentelekomcloud_vpc_eip_v1.this: Creating...
opentelekomcloud_vpc_v1.this: Creation complete after 7s [id=5c0ecbe5-e0f0-43ce-a790-531615ecc567]
opentelekomcloud_vpc_subnet_v1.this: Creating...
opentelekomcloud_vpc_subnet_v1.this: Still creating... [10s elapsed]
opentelekomcloud_vpc_subnet_v1.this: Creation complete after 14s [id=f151edb2-e16c-4bd0-aad4-a30d13a1a3d9]
╷
│ Error: error allocating EIP: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v1/6799a766398e4a93af289fab67f89d5f/publicips], error message: {"code":"VPC.0501","message":"PublicIp type is invalid."}
│ 
│   with opentelekomcloud_vpc_eip_v1.this,
│   on main.tf line 14, in resource "opentelekomcloud_vpc_eip_v1" "this":
│   14: resource "opentelekomcloud_vpc_eip_v1" "this" {
│ 
╵
```

**Comment by nfelger** [comment] 2022-05-23 13:43
(The motivation for creating the EIP separately is to make sure we can destroy and re-create the loadbalancer without risking to lose the IP address. If you know of another good way to achieve this, do let me know!)

**Comment by lego963** [comment] 2022-05-24 09:12
@nfelger `vpc_subnet_v1` data_source was copied from my tf files. So, it's ok that you don't have this subnet :D
I understand your request and I asked the squad members responsible for those components.

**Comment by lego963** [comment] 2022-05-24 10:26
@sfhl @nfelger updates. You can't create EIP `5_gray` with EIP apis (`resource/opentelekomcloud_vpc_eip_v1`). If you want to use ELBv3 with EIP you should create EIP with ELBv3 API (`resource/opentelekomcloud_lb_locabalancer_v3`)

Internal tickets exist: 
- https://jira.tsi-dev.otc-service.com/browse/ONS-5904 
- https://jira.tsi-dev.otc-service.com/browse/ONS-5905

**Comment by nfelger** [comment] 2022-06-02 09:23
@lego963 I only just saw your update. Just to make sure I understand the implications: there is no way to separately create the EIPs for an ELBv3 with terraform right now?

**Comment by lego963** [comment] 2022-06-02 09:27
@nfelger yes, you are right. (for now) The issue with EIP in `eu-de` will be fixed, but I don't have any time estimations there. :(

**Comment by nfelger** [comment] 2022-06-02 09:33
@lego963 Ok, thanks for the clarification!

**Comment by Aloento** [comment] 2022-08-25 21:06
Status:SELECTED FOR DEV

**Comment by anton-sidelnikov** [comment] 2023-07-28 17:22
Currently API fixed and EIP assignment works as described in documentation. Provider documentation will be updated.

**Closed as completed** 2023-08-21 09:50 UTC
